### ISSUE TITLE
Package does not work for new PSID data

### ISSUE THREAD

**Issue by KelingZ** [aaowens/PSID.jl#45] opened 2022-09-08 04:07 UTC
1. PSID code book 
The link provided in README.md for PSID code book (https://simba.isr.umich.edu/downloads/PSIDCodebook.zip) is broken. I downloaded PSID code book from PSID data center and came across the following error message when running the code:

ERROR: LightXML.XMLParseError{String}("Failure in parsing an XML file.")

<img width="1041" alt="Screen Shot 2022-09-07 at 9 08 00 PM" src="https://user-images.githubusercontent.com/46659820/189032233-c8536a8c-9a2a-4164-a2a1-132184e212cf.png">

Then I downloaded the xml PSID code book from the google drive link (https://drive.google.com/file/d/1nz1UaVGcj0ur2Bp3ev7a8agJbj0A5JTF/view), I can successfully make the codebook. 

The code does not seem to be compatible with the new PSID codebook format?

2. psid.xlsx 
The link provided in README.md for psid.xlsx still works. But the code has a problem reading in the xlsx file. 

ERROR: AssertionError: isempty(XML_GLOBAL_ERROR_STACK)
<img width="1056" alt="Screen Shot 2022-09-07 at 9 05 40 PM" src="https://user-images.githubusercontent.com/46659820/189032028-07e217f9-9e30-4f97-88c7-ed0e441adff4.png">

**Comment by aaowens** [comment] 2022-09-11 16:25
I think I know what the problem is for the PSID Codebook XML. There's an invalid character in variable V1350, in QTEXT.

Look here:

<YEAR>1970</YEAR>
          <TYPE_ID>1</TYPE_ID>
          <NAME>V1350</NAME>
          <LABEL>WTR WKD-69 (R)</LABEL>
          <QTEXT>F1.  During the last year (1969), did you (HEAD) do any work for money? (Retired, ...) (1970 question)</QTEXT>
          <ETEXT> </ETEXT>

and remove the invalid character. Then it should parse.

I can't check it right now, not at the right computer.

That's interesting that it can't parse the new XLSX. I'll have to look at it later.

**Comment by aaowens** [comment] 2022-09-18 23:57
I sent an email to the PSID people asking why the XML codebook is gone.

I'm currently updating all the package dependencies to the latest versions + Julia 1.8. With those changes, I was able to create a PSID dataset fine using my local copies of the data.

**Comment by aaowens** [comment] 2022-09-25 23:38
Hopefully fixed now, I tagged a new version of the package. There's a new link to the XML codebook in the readme

**Closed** 2024-02-28 03:25 UTC
